            - name: CodeThreat Scanner
  # You may pin to the exact commit or the version.
  # uses: CodeThreat/codethreat-github-action@89ccd1d539dc44a0c57aab95489f633eb93f7052
  uses: CodeThreat/codethreat-github-action@v1.021
  with:
    # FAILED_ARGS
    FAILED_ARGS: # optional, default is 
          
